disabled_rules:
- trailing_comma

opt_in_rules:

analyzer_rules:
- explicit_self
- unused_declaration
- unused_import

included:
- Packages

excluded:

allow_zero_lintable_files: false

strict: false

force_cast: warning

force_try:
  severity: warning

type_body_length:
  warning: 150
  error: 250

file_length:
  warning: 500
  error: 800

type_name:
  min_length: 3
  max_length:
    warning: 30
    error: 50
  excluded: iPhone
  allowed_symbols: [_]

identifier_name:
  min_length:
    error: 3
  excluded:
  - id
  - url
  - uid

nesting:
  type_level:
    warning: 3
    error: 5

reporter: relative-path # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
